In [3]:
import numpy as np

In [6]:
arr = np.arange(1,11)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
bool_arr = arr > 5

In [11]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [14]:
arr[arr<3]

array([1, 2])

In [16]:
arr_2d = np.arange(50).reshape(5,10)

In [17]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
arr_2d = np.arange(40).reshape(4,10)

In [19]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [20]:
arr_2d = np.arange(50).reshape(5,10)

In [21]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
arr_2d[arr_2d>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
arr_2d[3,7:]

array([37, 38, 39])

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [31]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [32]:
arr/arr

C:\Users\annabel.peel\AppData\Local\Temp\ipykernel_18060\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
1/arr

C:\Users\annabel.peel\AppData\Local\Temp\ipykernel_18060\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [34]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [35]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [36]:
np.max(arr)

10

In [37]:
arr.max()

10

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [39]:
np.log(arr)

C:\Users\annabel.peel\AppData\Local\Temp\ipykernel_18060\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [40]:
import numpy as np

In [41]:
import pandas as pd

In [43]:
labels = ["a","b","c"]
my_data = [10,20,30]
arr = np.array(my_data)
d = {"a":10,"b":20,"c":30}

In [44]:
labels

['a', 'b', 'c']

In [45]:
my_data

[10, 20, 30]

In [46]:
arr

array([10, 20, 30])

In [47]:
d

{'a': 10, 'b': 20, 'c': 30}

In [48]:
pd.Series(data = my_data)

##pandas series 

0    10
1    20
2    30
dtype: int64

In [49]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [50]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [52]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [53]:
type(arr)

numpy.ndarray

In [54]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [59]:
ser1 = pd.Series([1,2,3,4],["USA","Germany","USSR","Japan"])

In [60]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [61]:
ser2 = pd.Series([1,2,5,4],["USA","Germany","Italy","Japan"])

In [62]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [68]:
ser1["Germany"]

2

In [69]:
ser3 = pd.Series(data=labels)

In [70]:
ser3

0    a
1    b
2    c
dtype: object

In [71]:
ser3[0]

'a'

In [72]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [73]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [74]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [75]:
import numpy as np
import pandas as pd

In [76]:
from numpy.random import randn

In [77]:
np.random.seed(101)

In [78]:
df = pd.DataFrame(randn(5,4),["A","B","C","D","E"],["W","X","Y","Z"])

In [79]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [80]:
df["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [83]:
type(df["W"])

pandas.core.series.Series

In [84]:
type(df)

pandas.core.frame.DataFrame

In [85]:
df["X"]

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [87]:
df["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [88]:
df[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [90]:
df["new"] = df["W"] + df["Y"]

In [91]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [96]:
df.drop("new", axis=1,inplace=True)

In [97]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [98]:
df.drop("E")

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [100]:
df.shape ##rows are 0 axis and columns are 1 axis 

(5, 4)

In [101]:
df[["Z","X"]]

Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [102]:
#ROWS

In [104]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [105]:
df.loc["A"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [107]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [108]:
df.loc["B","Y"]

-0.8480769834036315

In [109]:
df.loc[["A","B"],["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [110]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [111]:
df > 0 ##returns boolean values 

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [112]:
booldf = df > 0

In [113]:
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [114]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [115]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [117]:
df["W"]>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [119]:
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [121]:
df[df["Z"]<0] ##value less than 0 in column Z is in row c
#returns all of row c

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [123]:
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [125]:
resultdf = df[df["W"]>0]

In [127]:
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [128]:
resultdf["X"]

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [130]:
df[df["W"]>0][["Y","X"]]  ##both steps in one, filter out columnc C first, then grab column X

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [135]:
boolser = df["W"]>0
result = df[boolser]
result[["Y","X"]]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [134]:
result

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509